services:
  - type: web
    name: ueh-e-lunch
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: STAFF_PIN
        generateValue: true
